### ISSUE TITLE
Tracking Issues: Zig Upstream

### ISSUE THREAD

**Issue by kassane** [kassane/anotherBuildStep#8]
## Follow

- [ ] https://github.com/ziglang/zig/issues/20875
- [x] https://github.com/ziglang/zig/issues/2879
- [ ] https://github.com/ziglang/zig/issues/20327
- [ ] https://github.com/ziglang/zig/issues/20042
- [ ] https://github.com/ziglang/zig/issues/18018
- [ ] https://github.com/ziglang/zig/issues/14286
- [x] https://github.com/ziglang/zig/issues/20235
- [x] https://github.com/ziglang/zig/issues/20129
- [x] https://github.com/ziglang/zig/issues/19725
- [ ] https://github.com/ziglang/zig/issues/19859
- [ ] https://github.com/ziglang/zig/issues/18877
- [ ] https://github.com/ziglang/zig/issues/18450
- [ ] https://github.com/ziglang/zig/issues/18439
- [ ] https://github.com/ziglang/zig/issues/17472
- [x] https://github.com/ziglang/zig/issues/17895
- [x] https://github.com/ziglang/zig/pull/19684
- [x] https://github.com/ziglang/zig/pull/20580
- [x] https://github.com/ziglang/zig/issues/19570
- [x] https://github.com/ziglang/zig/issues/20630
- [x] https://github.com/ziglang/zig/issues/14531
- [ ] https://github.com/ziglang/zig/issues/20690
- [x] https://github.com/ziglang/zig/pull/17956
- [x] https://github.com/ziglang/zig/issues/23665
- [ ] https://github.com/ziglang/zig/issues/22663
- [ ] https://github.com/ziglang/zig/issues/3936
- https://github.com/ziglang/zig/issues/20981
